### ISSUE TITLE
namedstruct.Message construction

### ISSUE THREAD

**Issue by zakjwalton** [sprout42/StarStruct#2]
When creating a `Message` with a variable length field where the length of the field is specified, should there be an automatic check for if the actual length of the `field` is equal to the `field_len`?

``` python
our_msg = namedstruct.Message('name', [
    ('field_len', 'B', 'field'),
    ('field', FieldType, 'fileld_len'),
])
```

**Comment by sprout42** [comment]
When doing a pack on this message, the `field_len` element could be missing from the object passed in:
`packed = our_msg.pack({'field': [1, 2]})`

This would automatically fill in the value of the `field_len` place in the packed message with the length of the 'field' element.  When doing an unpack the `field_len` value is used to determine how many `field` elements to unpack.

I don't really like the current way that the length and variable elements have to reference each other, it feels clunky at the moment.  I hope to figure out a more intuitive method eventually.
