### ISSUE TITLE
Update project structure to the latest template

### ISSUE THREAD

**Issue by jacebrowning** [sprout42/StarStruct#21]
I'd be happy to send a PR your way after the project gets renamed (https://github.com/sprout42/NamedStruct/issues/10).

**Comment by sprout42** [comment]
Rename is complete, go ahead and push changes.  Especially to fix all the travis stuff that I probably broke when I did the original project :)

**Comment by jacebrowning** [comment]
Sounds good! Can I be added as a collaborator?

**Comment by sprout42** [comment]
Coming right up...
