### ISSUE TITLE
Add badges?

### ISSUE THREAD

**Issue by jacebrowning** [sprout42/StarStruct#26]
https://github.com/sprout42/StarStruct/pull/25 updated the tooling necessary to use TravisCI, Coveralls (tracks coverage over time), and Scrutinizer (tracks code quality over time).

TravisCI is already functioning and a badge can be addd from:
- https://travis-ci.org/sprout42/StarStruct

The other services need to be activated first:
- https://coveralls.io/github/sprout42/StarStruct
- https://scrutinizer-ci.com/g/new

**Comment by sprout42** [comment]
Enabling them now

**Comment by sprout42** [comment]
Any idea why the coveralls badge might be saying unknown?  I see 78% if I follow the link.

**Comment by sprout42** [comment]
weird it seems to show up sometimes...

Anyway, registered with pypi now also!
https://pypi.python.org/pypi/StarStruct

**Comment by jacebrowning** [comment]
It looks correct to me:

<img width="414" alt="screen shot 2016-10-18 at 10 25 36 am" src="https://cloud.githubusercontent.com/assets/939501/19481831/3b863712-951d-11e6-8bf0-b5fa19212742.png">

GitHub aggressively caches images so somethings you need to do a hard refresh.
